# Generated by Django 4.2.23 on 2025-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jan_code', models.CharField(max_length=30)),
                ('Product_number', models.CharField(max_length=30, null=True)),
                ('Brand_name', models.CharField(max_length=256)),
                ('SKU_number', models.CharField(max_length=256)),
                ('Product_name', models.CharField(max_length=256)),
                ('English_name', models.CharField(max_length=256, null=True)),
                ('Rassian_name', models.CharField(max_length=256, null=True)),
                ('Contents', models.CharField(max_length=256, null=True)),
                ('Volume', models.CharField(max_length=256, null=True)),
                ('Case_qty', models.CharField(max_length=256, null=True)),
                ('Lot', models.CharField(max_length=256, null=True)),
                ('Oeder', models.CharField(max_length=256, null=True)),
                ('Unit_price', models.CharField(max_length=256, null=True)),
                ('Amount', models.CharField(max_length=256, null=True)),
                ('Case_volume', models.CharField(max_length=256, null=True)),
                ('Case_weight', models.CharField(max_length=256, null=True)),
                ('Case_qty2', models.CharField(max_length=256, null=True)),
                ('TTL_volume', models.CharField(max_length=256, null=True)),
                ('TTL_weight', models.CharField(max_length=256, null=True)),
                ('Product_size', models.CharField(max_length=256, null=True)),
                ('Unit_nw', models.CharField(max_length=256, null=True)),
                ('TTL_nw', models.CharField(max_length=256, null=True)),
                ('Ingredients', models.CharField(max_length=256, null=True)),
                ('DS_details', models.CharField(max_length=256, null=True)),
                ('DS_brandname', models.CharField(max_length=256, null=True)),
                ('DS_Manufacturer', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
