# Generated by Django 4.2.23 on 2025-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YAMATO_TOYO_ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=256, null=True)),
                ('Order_Code', models.CharField(max_length=256, null=True)),
                ('Item_Name', models.CharField(max_length=256, null=True)),
                ('Quantity', models.CharField(max_length=256, null=True)),
                ('Unit_price_JPY', models.CharField(max_length=256, null=True)),
                ('Amount_JPY', models.CharField(max_length=256, null=True)),
                ('販売価格', models.CharField(max_length=256, null=True)),
                ('輸出額', models.CharField(max_length=256, null=True)),
                ('利益', models.CharField(max_length=256, null=True)),
                ('利益率', models.CharField(max_length=256, null=True)),
                ('pcs_ct', models.CharField(max_length=256, null=True)),
                ('CTN', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
