# Generated by Django 4.2.23 on 2025-09-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YAMATO_TOYO_OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=256, null=True)),
                ('Order_Code', models.CharField(max_length=256, null=True)),
                ('Item_Name', models.CharField(max_length=256, null=True)),
                ('Quantity', models.CharField(max_length=256, null=True)),
                ('Unit_price_JPY', models.CharField(max_length=256, null=True)),
                ('Amount_JPY', models.CharField(max_length=256, null=True)),
                ('販売価格', models.CharField(max_length=256, null=True)),
                ('輸出額', models.CharField(max_length=256, null=True)),
                ('利益', models.CharField(max_length=256, null=True)),
                ('利益率', models.CharField(max_length=256, null=True)),
                ('pcs_ct', models.CharField(max_length=256, null=True)),
                ('CTN', models.CharField(max_length=256, null=True)),
                ('RequiredProduct_flg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yamato_toyo_items', to='kseurasia_manage_app.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='NIPPONIKATRADING_OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HS_CODE', models.CharField(max_length=256, null=True)),
                ('Jan_code', models.CharField(max_length=30, null=True)),
                ('Артикул', models.CharField(max_length=256, null=True)),
                ('Brand_name', models.CharField(max_length=256, null=True)),
                ('日本語名', models.CharField(max_length=256, null=True)),
                ('Description_of_goods', models.CharField(max_length=256, null=True)),
                ('Наименование_ДС_англ', models.CharField(max_length=256, null=True)),
                ('Наименование_ДС_рус', models.CharField(max_length=256, null=True)),
                ('Contents', models.CharField(max_length=256, null=True)),
                ('LOT', models.CharField(max_length=256, null=True)),
                ('Case_Qty', models.CharField(max_length=256, null=True)),
                ('ORDER', models.CharField(max_length=256, null=True)),
                ('Unit_price', models.CharField(max_length=256, null=True)),
                ('Amount', models.CharField(max_length=256, null=True)),
                ('仕入値', models.CharField(max_length=256, null=True)),
                ('仕入値合計', models.CharField(max_length=256, null=True)),
                ('利益', models.CharField(max_length=256, null=True)),
                ('利益率', models.CharField(max_length=256, null=True)),
                ('ケース容積', models.CharField(max_length=256, null=True)),
                ('ケース重量', models.CharField(max_length=256, null=True)),
                ('ケース数量', models.CharField(max_length=256, null=True)),
                ('合計容積', models.CharField(max_length=256, null=True)),
                ('合計重量', models.CharField(max_length=256, null=True)),
                ('商品サイズ', models.CharField(max_length=256, null=True)),
                ('Unit_NW', models.CharField(max_length=256, null=True)),
                ('Total_NW', models.CharField(max_length=256, null=True)),
                ('成分', models.CharField(max_length=256, null=True)),
                ('Марка_бренд_ДС', models.CharField(max_length=256, null=True)),
                ('Производель_ДС', models.CharField(max_length=256, null=True)),
                ('RequiredProduct_flg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nipponika_items', to='kseurasia_manage_app.importbatch')),
            ],
        ),
    ]
