# Generated by Django 4.2.23 on 2025-08-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0002_ordercontent_created_at_ordercontent_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=128)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='kseurasia_manage_app.importbatch'),
        ),
    ]
