# Generated by Django 4.2.23 on 2025-09-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0002_yamato_toyo_ordercontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontent',
            name='日本語名',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ry_productinfo',
            name='日本語名',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
