# Generated by Django 4.2.23 on 2025-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0003_ordercontent_日本語名_ry_productinfo_日本語名'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamato_toyo_ordercontent',
            name='総販売価格',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
