# Generated by Django 4.2.23 on 2025-08-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0003_importbatch_ordercontent_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='Brand_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='Jan_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='Product_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='SKU_number',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
