# Generated by Django 4.2.23 on 2025-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0004_alter_ordercontent_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontent',
            name='Purchase_amount',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='Purchase_price',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='profit',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='profit_rate',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
