# Generated by Django 4.2.23 on 2025-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0004_yamato_toyo_ordercontent_総販売価格'),
    ]

    operations = [
        migrations.AddField(
            model_name='nipponikatrading_productinfo',
            name='RequiredProduct_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ry_productinfo',
            name='RequiredProduct_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yamato_toyo_productinfo',
            name='RequiredProduct_flg',
            field=models.BooleanField(default=False),
        ),
    ]
