# Generated by Django 3.2.25 on 2025-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0005_nipponikatrading_productinfo_requiredproduct_flg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nipponikatrading_ordercontent',
            name='成分',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nipponikatrading_productinfo',
            name='成分',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='Ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ry_productinfo',
            name='Ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
