# Generated by Django 4.2.23 on 2025-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0005_ordercontent_purchase_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontent',
            name='Order',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
