# Generated by Django 3.2.25 on 2025-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0006_auto_20250924_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='DS_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ry_productinfo',
            name='DS_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
