# Generated by Django 4.2.23 on 2025-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0006_ordercontent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='InvoicePacking_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='PurchaseOrder_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
