# Generated by Django 3.2.25 on 2025-09-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0007_auto_20250924_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nipponikatrading_ordercontent',
            name='成分',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='nipponikatrading_productinfo',
            name='成分',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='DS_details',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='Ingredients',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ry_productinfo',
            name='DS_details',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ry_productinfo',
            name='Ingredients',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
