# Generated by Django 4.2.23 on 2025-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0007_importbatch_invoicepacking_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontent',
            name='supplier',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
