# Generated by Django 4.2.23 on 2025-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0008_ordercontent_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercontent',
            name='supplier',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='buyers',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
