# Generated by Django 4.2.23 on 2025-09-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kseurasia_manage_app', '0009_remove_ordercontent_supplier_importbatch_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontent',
            name='RequiredProduct_flg',
            field=models.BooleanField(default=False),
        ),
    ]
